"""Add task_types table

Revision ID: 62ae3ce6ab05
Revises: 
Create Date: 2025-01-22 11:27:29.773016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ae3ce6ab05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_types_id'), 'task_types', ['id'], unique=False)
    op.create_index(op.f('ix_task_types_name'), 'task_types', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_types_name'), table_name='task_types')
    op.drop_index(op.f('ix_task_types_id'), table_name='task_types')
    op.drop_table('task_types')
    # ### end Alembic commands ###
